### ISSUE TITLE
Backend access security worning

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#170]
When entring backend, browser say that ID can not be trusted and gives a security worning.

**Comment by MeanEYE** [comment]
This site is using development version of Caracal, which is currently set to be 0.5. This version enforces secure protocol when accessing backend. This is done to ensure no one catches password during login or while configuring the rest of the system. Warning you are getting is due to the fact they don't have signed security certificate installed on the server. Even so, security certificate is there and does its purpose, only thing browser is warning users about is that certificate can't be trusted fully. That said, this is not a bug nor an issue. Annoyance perhaps, but it's for the better as some form of encryption is still better than no encryption.
