### ISSUE TITLE
Images are missing their title as alt 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#29]
http://bsexy.co.il.82-223-16-124.eu1.way2cu.work/gays/gays-tiberius/3
Images should have atl tag with their name

**Comment by MeanEYE** [comment]
Images are getting their titles properly set. The problem on the page is that images don't have titles assigned in backend. For the sake of SEO we opted for this approach instead of using shop item title in there. 

As seen on this local test I did, `alt` attribute is properly set from image title in backend.
![screenshot from 2016-10-24 20-45-14](https://cloud.githubusercontent.com/assets/1911594/19659096/d19ac7c4-9a2a-11e6-93a1-a6a3afa30d3a.png)
