### ISSUE TITLE
Images size and background problems

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#67]
At item's page the images are always with a created background, htere should only be one when image is not the right size. If image is the right size it should be the entire space and without background shown.
When opening image in another tab, its always the same image, that should be changed to open the right one.

**Comment by MeanEYE** [comment]
Translated from Hananistanic language it means images are at 400px when they should be the same size as container, which is 600px. Also, this is a two part problem. You need to apply `visibility: hidden` instead of just `opacity: 0` for hidden images. This is because fully transparent images are still present in and receive events. Which in this case is the right click @hanan-avzuk is talking about.
