### ISSUE TITLE
Poor PageSpeed insights score for mobile version of the site.

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#92]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fbsexy.co.il%2F&tab=mobile

Mobile is 54/100 ??????

**Comment by MeanEYE** [comment]
Useless shit titles like these shouldn't repeat ever. As for the issue itself it looks like Google really wants us to reduce image size to absolute minimum. This is something I've instructed not to be done due to screens having huge screen resolutions these days. Not sure why Google would decide to punish that so suddenly.

**Comment by talrez11** [comment]
When calling src="gallery::getThumbnailById($params['image'], null, 300,Thumbnail::CONSTRAIN_WIDTH)", am not able to generate thumbnail of shop category

**Comment by talrez11** [comment]
Site should be tested once deployed
